
CREATE DATABASE PD_311_HW
ON 
(
	NAME = PD_311_DDL_dat,
	FILENAME='B:\SQL base\HW\PD_311_DDL.mdf',
	SIZE = 8MB, 
	MAXSIZE = 512MB, 
	FILEGROWTH = 8MB
)
LOG ON
(
	NAME = PD_311_DDL_log,
	FILENAME='B:\SQL base\HW\PD_311_DDL.ldf',
	SIZE = 8MB,
	MAXSIZE = 512MB,
	FILEGROWTH = 8MB
);
